### ISSUE TITLE
Screeshots of Registration page, Output in browser and flask console

### ISSUE THREAD

**Issue by sailaja23595** [sailaja23595/project-1#3]
![Register](https://user-images.githubusercontent.com/55689035/79445270-03c4c480-7ffa-11ea-89b4-cc679420d719.PNG)
![Output1](https://user-images.githubusercontent.com/55689035/79445596-8d749200-7ffa-11ea-8473-807f86a9637c.PNG)
![py display](https://user-images.githubusercontent.com/55689035/79445622-96fdfa00-7ffa-11ea-8dda-e573a48c9b24.PNG)

**Comment by ChaitanyaPuritipati** [comment]
Good work
