### ISSUE TITLE
Registration form with alerts and output of administration page

### ISSUE THREAD

**Issue by sailaja23595** [sailaja23595/project-1#5]
![reg success](https://user-images.githubusercontent.com/55689035/79681474-2a703e80-8238-11ea-9d23-d01be546dc45.PNG)
![Reg already exist](https://user-images.githubusercontent.com/55689035/79681477-2fcd8900-8238-11ea-84ec-f9f52fcccea0.PNG)
![admin](https://user-images.githubusercontent.com/55689035/79681482-34923d00-8238-11ea-90a0-0a6095e9418d.PNG)

**Comment by ChaitanyaPuritipati** [comment]
Good work. You can start working on authentication
